---
# tasks file for ansible-xfreemfs-client

- include: main-RedHat.yml
  when: ansible_os_family == "RedHat"
- include: main-Debian.yml
  when: ansible_os_family == "Debian"
- shell: mkfs.xtreemfs {{tinc_ip}}/web
  with_items: xtreemfs_volumes
  failed_when: False
  when: xtreemfs_role == "server"