---
# tasks file for ansible-xfreemfs-client

- name: install the xfreemfs repo
  apt_repository: repo="deb-src http://download.opensuse.org/repositories/home:/xtreemfs/Debian_8.0/ ./" state=present

- name: "install gpg key"
  apt_key: url=http://download.opensuse.org/repositories/home:/xtreemfs/xUbuntu_16.04/Release.key

- name: install xfreemfs-server
  yum: name=xtreemfs-server state=present
  when: xtreemfs_role == "server"

- name: start and enable xtreemfs-dir
  service: name=xtreemfs-dir state=started enabled=yes
  when: xtreemfs_role == "server"

- name: start and enable xtreemfs-mrc
  service: name=xtreemfs-mrc state=started enabled=yes
  when: xtreemfs_role == "server"

- name: start and enable xtreemfs-osd
  service: name=xtreemfs-osd state=started enabled=yes
  when: xtreemfs_role == "server"

- name: install xfreemfs-client
  yum: name=xtreemfs-client state=present
  when: xtreemfs_role == "client"

- name: install xfreemfs-tools
  yum: name=xtreemfs-tools state=present
  when: xtreemfs_role == "client"
