---
# tasks file for ansible-xfreemfs-client

- name: install the xfreemfs repo
  apt_repository: repo="deb http://download.opensuse.org/repositories/home:/xtreemfs/Debian_8.0/ ./" state=present

- name: "install gpg key"
  apt_key: id=07D6EA4F2FA7E736 url=http://download.opensuse.org/repositories/home:/xtreemfs/xUbuntu_16.04/Release.key

- name: install xfreemfs-server
  apt: name=xtreemfs-server state=present
  when: xtreemfs_role == "server"

- name: start and enable xtreemfs-dir
  service: name=xtreemfs-dir state=started enabled=yes
  when: xtreemfs_role == "server"

- name: start and enable xtreemfs-mrc
  service: name=xtreemfs-mrc state=started enabled=yes
  when: xtreemfs_role == "server"

- name: start and enable xtreemfs-osd
  service: name=xtreemfs-osd state=started enabled=yes
  when: xtreemfs_role == "server"

- name: install xtreemfs-client
  apt: name=xtreemfs-client state=present
  when: xtreemfs_role == "client"

- name: install xtreemfs-tools
  apt: name=xtreemfs-tools state=present
  when: xtreemfs_role == "client"
